import { GateType } from '../../engine/types';
import type { Level } from '../Level';

export const level263BitDecoder: Level = {
  id: '26-3-bit-decoder',
  name: '3 Bit Decoder',
  section: 'Arithmetic and Memory',
  prerequisites: ['25-1-bit-decoder'],
  description:
    'Choose between eight outputs using three inputs. Decode a 3-bit value to one of 8 output lines.',
  availableGates: [GateType.AND, GateType.NOT],
  inputs: [{ name: 'Bit 2' }, { name: 'Bit 1' }, { name: 'Bit 0' }],
  outputs: [
    { name: 'O0' },
    { name: 'O1' },
    { name: 'O2' },
    { name: 'O3' },
    { name: 'O4' },
    { name: 'O5' },
    { name: 'O6' },
    { name: 'O7' },
  ],
  truthTable: [
    {
      inputs: { 'Bit 2': false, 'Bit 1': false, 'Bit 0': false },
      outputs: {
        O0: true,
        O1: false,
        O2: false,
        O3: false,
        O4: false,
        O5: false,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': false, 'Bit 1': false, 'Bit 0': true },
      outputs: {
        O0: false,
        O1: true,
        O2: false,
        O3: false,
        O4: false,
        O5: false,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': false, 'Bit 1': true, 'Bit 0': false },
      outputs: {
        O0: false,
        O1: false,
        O2: true,
        O3: false,
        O4: false,
        O5: false,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': false, 'Bit 1': true, 'Bit 0': true },
      outputs: {
        O0: false,
        O1: false,
        O2: false,
        O3: true,
        O4: false,
        O5: false,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': true, 'Bit 1': false, 'Bit 0': false },
      outputs: {
        O0: false,
        O1: false,
        O2: false,
        O3: false,
        O4: true,
        O5: false,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': true, 'Bit 1': false, 'Bit 0': true },
      outputs: {
        O0: false,
        O1: false,
        O2: false,
        O3: false,
        O4: false,
        O5: true,
        O6: false,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': true, 'Bit 1': true, 'Bit 0': false },
      outputs: {
        O0: false,
        O1: false,
        O2: false,
        O3: false,
        O4: false,
        O5: false,
        O6: true,
        O7: false,
      },
    },
    {
      inputs: { 'Bit 2': true, 'Bit 1': true, 'Bit 0': true },
      outputs: {
        O0: false,
        O1: false,
        O2: false,
        O3: false,
        O4: false,
        O5: false,
        O6: false,
        O7: true,
      },
    },
  ],
  hints: [
    'Each output needs a unique combination of AND and NOT gates',
    'Use NOT to invert each input, then AND together the right combination for each output',
  ],
};
