import { GateType } from '../../engine/types';
import type { Level } from '../Level';

export const level263BitDecoder: Level = {
  id: '26-3-bit-decoder',
  name: '3 Bit Decoder',
  section: 'Arithmetic and Memory',
  prerequisites: ['25-1-bit-decoder'],
  unlocks: ['27-logic-engine', '40-registers'],
  description:
    'Choose between eight outputs using three inputs. Decode a 3-bit value to one of 8 output lines.',
  availableGates: [GateType.AND, GateType.NOT],
  inputs: [{ name: 'Bit 0' }, { name: 'Bit 1' }, { name: 'Bit 2' }],
  outputs: [
    { name: 'Output 0' },
    { name: 'Output 1' },
    { name: 'Output 2' },
    { name: 'Output 3' },
    { name: 'Output 4' },
    { name: 'Output 5' },
    { name: 'Output 6' },
    { name: 'Output 7' },
  ],
  truthTable: [
    {
      inputs: { 'Bit 0': false, 'Bit 1': false, 'Bit 2': false },
      outputs: {
        'Output 0': true,
        'Output 1': false,
        'Output 2': false,
        'Output 3': false,
        'Output 4': false,
        'Output 5': false,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': true, 'Bit 1': false, 'Bit 2': false },
      outputs: {
        'Output 0': false,
        'Output 1': true,
        'Output 2': false,
        'Output 3': false,
        'Output 4': false,
        'Output 5': false,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': false, 'Bit 1': true, 'Bit 2': false },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': true,
        'Output 3': false,
        'Output 4': false,
        'Output 5': false,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': true, 'Bit 1': true, 'Bit 2': false },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': false,
        'Output 3': true,
        'Output 4': false,
        'Output 5': false,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': false, 'Bit 1': false, 'Bit 2': true },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': false,
        'Output 3': false,
        'Output 4': true,
        'Output 5': false,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': true, 'Bit 1': false, 'Bit 2': true },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': false,
        'Output 3': false,
        'Output 4': false,
        'Output 5': true,
        'Output 6': false,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': false, 'Bit 1': true, 'Bit 2': true },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': false,
        'Output 3': false,
        'Output 4': false,
        'Output 5': false,
        'Output 6': true,
        'Output 7': false,
      },
    },
    {
      inputs: { 'Bit 0': true, 'Bit 1': true, 'Bit 2': true },
      outputs: {
        'Output 0': false,
        'Output 1': false,
        'Output 2': false,
        'Output 3': false,
        'Output 4': false,
        'Output 5': false,
        'Output 6': false,
        'Output 7': true,
      },
    },
  ],
  hints: [
    'Each output needs a unique combination of AND and NOT gates',
    'Use NOT to invert each input, then AND together the right combination for each output',
  ],
};
